### ISSUE TITLE
Units for Event Depth Are Incorrect

### ISSUE THREAD

**Issue by smithj382** [usgs/groundmotion-processing#1029]
**Describe the bug**

gmprocess is designed to handle units of both m and km for event depth. When creating the obspy Origin object units for depth are expected to be in m, so the code converts depth from km to m here:  [Click Me](https://github.com/usgs/groundmotion-processing/blob/main/src/gmprocess/utils/event.py#:~:text=resource_id%3Did%2C%20time%3Dtime%2C%20longitude%3Dlon%2C%20latitude%3Dlat%2C%20depth%3Ddepth%20*%201000)

However viewing the origin object that is read from the ASDF file using the getEvent method shows the depth is being stored in km (34.9), not m. This leads to the wrong depth being outputted in mtables (because origin.depth_km takes origin.depth and divides by 1000). 

I am confused about why the Origin object is not saving the depth in the correct units. From my tests, I can save the depth to a different value if I feed it a float (constant depth=34900.0), but if I give it depth*1000 (or depth*1000. or float(depth)*1000) the units are always saved as km in the eventobj in ASDF. So I'm not sure where this issue stems from and am would like someone with more expertise to advise on an appropriate resolution.

**To Reproduce**
```gmrecords download -e ak022ctr3qn3;gmrecords assemble;gmrecords process;gmrecords sm;gmrecords mtables```

Check the event csv file and it should show depth as 0.03 (correct value is 34.9)

**Comment by smithj382** [comment]
Cannot reproduce this with the latest version of gmprocess.

**Comment by emthompson-usgs** [comment]
That is mysterious. I don't think we've done anything in the recent changes to affect this. But, if it isn't happening anymore, that's great!
