### ISSUE TITLE
Add overwrite option for generate_report

### ISSUE THREAD

**Issue by kallstadt-usgs** [usgs/groundmotion-processing#1046]
**Is your feature request related to a problem? Please describe.**
If I want to remake plots and reports after changing some processing options, for example, if the /plots folder already exists, the code crashes (FileExistsError: [Errno 17] File exists: 'somefolder/data/us6000hynr/plots'). Right now the fix is to manually delete the plots folder before running.

**Describe the solution you'd like**
Add an overwrite option flag (-o) like other commands have to generate_report

**Comment by baagaard-usgs** [comment]
Do you want an overwrite flag or should the default be to just overwrite?

**Comment by emthompson-usgs** [comment]
That's a good point. I don't see a downside to having the default be to overwrite.
