### ISSUE TITLE
Changing the array type to logspace for spectral acceleration in the config file does not work.

### ISSUE THREAD

**Issue by bartikpandel** [usgs/groundmotion-processing#1062]
For spectral acceleration calculation, if the array for periods is set to logspace in the config.yml file, I believe nothing is returned as my plot for SA vs period does not show anything. However, for linspace, the data is plotted correctly.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/74997802/200922247-a3a7de2c-a068-4efa-af2e-92ce43fcad3f.png">

**Comment by emthompson-usgs** [comment]
@bartikpandel  Thanks for the report. I will look into this, but can you clarify what plots for SA you are referring to? Is it a custom plot that you make from the output of the `export_metric_tables` subcommand? Or are you grabbing the SA from the h5 file? This info will help me figure out where the problem is.

**Comment by emthompson-usgs** [comment]
Note, I've copied this issue to gitlab: 
https://code.usgs.gov/ghsc/esi/groundmotion-processing/-/issues/1066

**Comment by emthompson-usgs** [comment]
@bartikpandel I believe that I've resolved this issue. Please install the from main on code.usgs.gov. Let me know if you have any further issues.

**Comment by bartikpandel** [comment]
> @bartikpandel I believe that I've resolved this issue. Please install the from main on code.usgs.gov. Let me know if you have any further issues.

@emthompson-usgs Thank you so much for this, Eric. My apologies for the late response. I will update the code from gitlab. Happy Holidays!
