### ISSUE TITLE
Error installing on macOS 11.4

### ISSUE THREAD

**Issue by dtdangkua** [usgs/groundmotion-processing#1065]
Hi,
I got an error while installing the code using the command below

`pip install .`

The error message at the end as follows,

"
      2 warnings and 3 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
Successfully built gmprocess
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects
"

h5py version: 1.12.2_2
python version: 3.11.0
OS: macOS 11.4
System: x86_64-apple-darwin20.6.0
Intel processor

Please advise.
Thanks.

Donny

**Comment by gferragu** [comment]
Hey @dtdangkua, I'd try backing down to an earlier version of Python and see if that works. It looks like the issue is actually because h5py [may not currently support wheels for Python 3.11](https://forum.hdfgroup.org/t/hi-newbie-here-having-some-trouble-with-installation/10379/2).

**Comment by gferragu** [comment]
Also,, @dtdangkua  note that the code has moved to https://code.usgs.gov/ghsc/esi/groundmotion-processing. At the moment it's difficult for public users to make issues on our Gitlab page, but we are working on a better solution and opening issues here in the meantime is fine

**Comment by gferragu** [comment]
Closing this for now unless I hear otherwise
