### ISSUE TITLE
Add rotation methods

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/groundmotion-processing#13]
- [x] RotD50
- [x] RotD100
- [x] GMRotD50
- [x] GMRotD100
- [ ] RotI50
- [ ] RotI100
- [ ] GMRotI50
- [ ] GMRotI100

As described by papers on [GMRotxx](http://www.daveboore.com/pubs_online/gmrot_bssa.pdf) and [Rotxx](http://www.daveboore.com/pubs_online/rotdxx_bssa_100.pdf) by Dave Boore.

**Comment by emthompson-usgs** [comment]
Closing because I think this is not necessary.
