### ISSUE TITLE
Add free_field property to StationTrace

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundmotion-processing#135]
This will inspect the structure_type standard header, and if it is blank or one of the free-field like lines in this set:

 - 'Small fiberglass shelter',
 - 'Small prefabricated metal bldg',
 - 'Sensors buried/set in ground',
 - 'Reference station',
 -  'Base of building',
 -  'Building',
 -  'Bridge',
 - 'Dam',
 - 'Other structure',
 - 'Geotechnical array',
 - 'Other array'
 - 'Roof of Building'
 - 'Borehole'
 - 'Basement of Building'

then return True, otherwise return False.

@emthompson-usgs Should we assume that basements are free field?

**Comment by emthompson-usgs** [comment]
I'm not sure. I think we will need to spend some time looking into this.
