### ISSUE TITLE
Add Turkey data parser and fetcher

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundmotion-processing#142]
The Turkish strong motion data website is back... for now. 

http://kyhdata.deprem.gov.tr/2K/kyhdata_v4.php

The format is actually pretty reasonable...

<snippet>
STRONG GROUND MOTION RECORDS OF TURKIYE
PLACE                   : İZMIR KARABURUN HALK EGITIM MERKEZI
EARTHQUAKE DATE         : 2019/03/17 00:23:47 (GMT)
EPICENTER COORDINATES   : 38.81350N-25.72980E
EARTHQUAKE DEPTH (km)   : 8.52
EARTHQUAKE MAGNITUDE    : 3.0 ML
STATION ID              : 3527
STATION COORDINATES     : 38.63903N-26.51277E
STATION ALTITUDE (m)    : 60
RECORDER TYPE           : Guralp cmg5td
RECORDER SERIAL NO      : T5C18/B249
RECORD TIME             : 17/03/2019 00:23:43.00 (GMT)
NUMBER OF DATA          : 8252
SAMPLING INTERVAL (sec) : 0.01
RAW PGA VALUES (gal)    : (N-S) 0.094015 (E-W) 0.073248 (U-D) 0.055919
Copyright EARTHQUAKE DEPARTMENT
DISASTER AND EMERGENCY MANAGEMENT PRESIDENCY
       N-S          E-W          U-D
   -0.000182      0.000038     0.000022
   -0.000187      0.000036     0.000027
</snippet>

**Comment by emthompson-usgs** [comment]
This would be a good shakemap to test and try to update with more records:
https://earthquake.usgs.gov/earthquakes/eventpage/us2000jkr3/executive
