### ISSUE TITLE
Implement Pphase picker as described by Kalkan BSSA 2016 "An Automatic P-Phase Arrival-Time Picker"

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundmotion-processing#179]
Bulletin of the Seismological Society of America, Vol. 106, No. 3, pp. 971–986, June 2016, doi: 10.1785/0120150111
An Automatic P-Phase Arrival-Time Picker by Erol Kalkan

Matlab code can be found here:

https://www.mathworks.com/matlabcentral/fileexchange/57729-an-automated-p-phase-arrival-time-picker-with-snr-output?s_tid=mwa_osa_a

**Comment by emthompson-usgs** [comment]
Closed by PR #190
