### ISSUE TITLE
process_events() takes origin dict as argument, but workspace holds ObsPy Origin object

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#202]
There is an inconsistency between how the origin is stored in the workspace and the origin argument for process_streams(). The workspace holds the earthquake metadata within QuakeML, so StreamWorkspace.getEvent() retiurns an ObsPy Event which holds an Origin object. However, the processing.process_streams() function takes the origin as a dict. I don't see a simple way to translate from one to the other.

In general there seems to be some inconsistency in how earthquake metadata is being passed around. Some places expect a dictionary and others expect an ObsPy Event object. I propose that we use ObsPy objects since this is how things are stored in the workspace.

**Comment by mhearne-usgs** [comment]
@baagaard-usgs This doesn't address the consistency issue, but we do have a function for converting a dictionary to an Obspy Event object:

https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/event.py#L35

**Comment by emthompson-usgs** [comment]
I'm assigning this to Release 1.0 project because I think it is important and we should address this soon.

**Comment by emthompson-usgs** [comment]
Closed by #237.
