### ISSUE TITLE
Rename datafetch to fetchevent

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundmotion-processing#207]
unless someone has a better idea

**Comment by emthompson-usgs** [comment]
How about "gmprocess" since it is kinda the main thing now, doing everything (fetching, reading, processing, metrics, etc).

**Comment by wald-usgs** [comment]
I'm good with "gmprocess". Better message than "smprocess".
djw

**Comment by emthompson-usgs** [comment]
If/when we make this change, lets keep `datafetch` around as an alias for a little while with a deprecation warning.

**Comment by emthompson-usgs** [comment]
Closed by #230.
