### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#210]
I thought we already had an open issue for this but I can't find it, so I'm creating this. 

@baagaard-usgs thinks we should get rid of the system config in `~/.gmprocess` and I think we are all in agreement on this. 

@mhearne-usgs already made this change in an in-progress branch, and `datafetch` currently takes an optional conf as an argument via the `-c` option. The conf need not have all sections; if a section is not present then it uses the defaults in the repo conf file. 

Also, @arkottke would also like to be able to set the conf in the local directory and have it be discovered by `datafetch`. This seems like a pretty reasonable change to me.

**Comment by arkottke** [comment]
The code from [matplotlib](https://github.com/matplotlib/matplotlib/blob/44952ed4c62c3d7a84f5aa487ca45b79f40f6bf7/lib/matplotlib/__init__.py#L642) is pretty straightforward and could be used as a starter: 
```Python
def matplotlib_fname():
    """
    Get the location of the config file.
    The file location is determined in the following order
    - ``$PWD/matplotlibrc``
    - ``$MATPLOTLIBRC`` if it is not a directory
    - ``$MATPLOTLIBRC/matplotlibrc``
    - ``$MPLCONFIGDIR/matplotlibrc``
    - On Linux,
        - ``$XDG_CONFIG_HOME/matplotlib/matplotlibrc`` (if ``$XDG_CONFIG_HOME``
          is defined)
        - or ``$HOME/.config/matplotlib/matplotlibrc`` (if ``$XDG_CONFIG_HOME``
          is not defined)
    - On other platforms,
        - ``$HOME/.matplotlib/matplotlibrc`` if ``$HOME`` is defined
    - Lastly, it looks in ``$MATPLOTLIBDATA/matplotlibrc``, which should always
      exist.
    """

    def gen_candidates():
        yield os.path.join(os.getcwd(), 'matplotlibrc')
        try:
            matplotlibrc = os.environ['MATPLOTLIBRC']
        except KeyError:
            pass
        else:
            yield matplotlibrc
            yield os.path.join(matplotlibrc, 'matplotlibrc')
        yield os.path.join(get_configdir(), 'matplotlibrc')
        yield os.path.join(get_data_path(), 'matplotlibrc')

    for fname in gen_candidates():
        if os.path.exists(fname) and not os.path.isdir(fname):
            return fname

    raise RuntimeError("Could not find matplotlibrc file; your Matplotlib "
                       "install is broken")
```

**Comment by emthompson-usgs** [comment]
The whole config thing has changed substantially since this issue was created. We now have support for both system level and directory-specific projects. I think the current system is working pretty well so I'm going to close this.
