### ISSUE TITLE
Units / process level issues

### ISSUE THREAD

**Issue by jrekoske-usgs** [usgs/groundmotion-processing#243]
Some related problems that I've noticed:
- Sometimes 'vel' is used and sometimes 'veloc' is used in tr.stats.standard.units. See https://github.com/usgs/groundmotion-processing/blob/1bbfb333aa393da4f672e761a456edbe3abba22e/gmprocess/stationtrace.py#L622 and https://github.com/usgs/groundmotion-processing/blob/1bbfb333aa393da4f672e761a456edbe3abba22e/gmprocess/metrics/metrics_controller.py#L353

There also is inconsistency in the meaning of tr.stats.standard.units. In StationTrace, the units are set based on the type of sensor ('acc' for accelerometers and 'vel' for everything else) even if it's raw data. But in calculating the stream metrics the tr.stats.standard.units need to be the units of the actual data to determine the workflow.

`processing.remove_response` will currently set a provenance entry called `remove_response` but it doesn't do anything to tr.stats.standard.units. Also, tr.stats.standard.process_level is never modified when calling `process_streams`

**Comment by emthompson-usgs** [comment]
The inconsistent units of `vel` and `veloc` is now resolved. But we have not addressed the `remove_response` part of this yet.
