### ISSUE TITLE
Refactor command line programs to take a more modular approach (a la ShakeMap)

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundmotion-processing#258]
Strawman proposal:
One program called gmprocess with positional "command" arguments (see below), and 5 "source" options:
-i eventid(s) ComCat event IDs to fetch/process
-t textfile containing either list of ComCat IDs or event info lines (id/time/lat/lon/dep/mag)
-e eventinfo Parameters to process one event (id/time/lat/lon/dep/mag)
--directory Directory containing data files and event.json

The command arguments could include, but are not limited to:

 - `download` Retrieve data from any online source available
 - `check` Perform pre-processing checks
 - `process` Perform data processing
 - `plot` Make diagnostic plots
 - `report` Generate per-event diagnostic report
 - `metrics` Generate per-event metrics table
 - `flatfile` (if appropriate) Generate multi-event NGA-style flatfile
 - `provenance` Generate per-event provenance spreadsheet

**Comment by emthompson-usgs** [comment]
Questions/comments:
- Conceptually, "metrics" and "flatfile" are basically the same thing. Right now, we have ended up with a convention where there are slight differences but really I think we don't need them to be separate things. 
- Would the `--directory` option support multiple events? If so, I think the directory would have to conform to a particular structure where data would be separated into event-specific subdirectories, and each would have an event.json file.

**Comment by mhearne-usgs** [comment]
- If we're going to combine flatfile/metrics, I think we'll want to possibly make the output more configurable
 - Yes, --directory would support multiple events, as you describe.

**Comment by baagaard-usgs** [comment]
I strongly support this approach; this is what I do in my own projects. The processing / analysis steps are controlled by positional arguments, so I can run one or more steps.

I would replace `flatfile` with `export`.

I would also add `all` which does all of the steps.

**Comment by emthompson-usgs** [comment]
I like that `flatfile` could be more generally be `export` and, and it could eventually export to different formats, such as a database or a flatfile.

**Comment by emthompson-usgs** [comment]
First pass at this is done with `gmprocess2`. We left `gmprocess` as is while we test out the new version.
