### ISSUE TITLE
Label handling in gmprocess

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#283]
gmprocess seems to just take the first label that is not "unprocessed":
https://github.com/usgs/groundmotion-processing/blob/master/bin/gmprocess2#L275
This may be fine for the work we've done so far in that we typically only have two labels, one for processed and one for unprocessed. But it isn't safe more generally.

**Comment by jrekoske-usgs** [comment]
I'm having label-handling problems without trying to use more than two labels. I'm running:

`gmprocess --assemble --process --export --directory bug -o output` 

giving the error
`Traceback (most recent call last):`
  `File "/Users/jrekoske/anaconda3/envs/gmprocess/bin/gmprocess", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))`
  `File "/Users/jrekoske/Repositories/groundmotion-processing/bin/gmprocess", line 480, in <module>
    main(pargs)`
 `File "/Users/jrekoske/Repositories/groundmotion-processing/bin/gmprocess", line 268, in main
    labels.remove('unprocessed')`
`ValueError: list.remove(x): x not in list`

It seems that the 'unprocessed' labeled streams are not being added to the workspace. Breaking up the --assemble, --process, and --export commands also gives the same error. Data is attached.
[bug.zip](https://github.com/usgs/groundmotion-processing/files/3352617/bug.zip)
