### ISSUE TITLE
Generic model of noise

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#29]

**Comment by jrekoske-usgs** [comment]
Obspy has some handy functions for this if we decide this is something we want to implement.
See https://docs.obspy.org/packages/autogen/obspy.signal.spectral_estimation.get_nlnm.html#obspy.signal.spectral_estimation.get_nlnm 
and
https://docs.obspy.org/packages/autogen/obspy.signal.spectral_estimation.get_nhnm.html#obspy.signal.spectral_estimation.get_nhnm
