### ISSUE TITLE
Add --failures argument to gmprocess

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#327]
Right now, it is not so easy to get a list of stations that failed processing and the reason for the failure. We should add a `--failures` command that would output a table with the station id, associated file names, and the failure reason. Format of the table will be a little tricky because there will be many files for a given station, and the actual number will vary with station.

**Comment by baagaard-usgs** [comment]
I propose we offer two (or more) levels of detail for this option:

1. Bare minimum info on the number of stations and channels that passed and failed.
2. Full failure info as described above with station id, channels, and failure reason.
