### ISSUE TITLE
Broadband records failing zero crossing test

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#349]
I am trying to process records for the M4.3 Livermore earthquake (nc73225421). Many of the broadband (BH*) channels are failing the zero crossing test. I tried reducing the min crossings to 0.2 and even 1.0e-10 and they are still failing. The signal to noise ratio looks very good. I am not sure this test is applicable in these cases.

[zerocrossing_nc73225421.zip](https://github.com/usgs/groundmotion-processing/files/3402676/zerocrossing_nc73225421.zip)

**Comment by emthompson-usgs** [comment]
Can you confirm that you demean the data in the processing section of the config file priort to applying the zero crossing check?

**Comment by emthompson-usgs** [comment]
Nevermind. I just ran it myself and see that it is failing even after demean. I'll look into this.

**Comment by emthompson-usgs** [comment]
In the mean time, if I were you, I'd just turn off the zero crossings check so that you can proceed.

**Comment by emthompson-usgs** [comment]
When I run it here, I get crossing rates all about 0.4 to 0.96. If I lower the min_crossings in the conf to 0.1, all of these records pass.

**Comment by baagaard-usgs** [comment]
Using a zero crossing rate of 0.1 worked. I must have boggled something when a very small zero crossing rate failed.
