### ISSUE TITLE
StationSumary fromMetricXML error

### ISSUE THREAD

**Issue by jrekoske-usgs** [usgs/groundmotion-processing#369]
This line is giving the error
AttributeError: type object 'StationSummary' has no attribute 'fromMetricXML'

https://github.com/usgs/groundmotion-processing/blob/37655de8e5bdf19852533f96f16712358098d8c7/gmprocess/io/asdf/stream_workspace.py#L477

I think we may have renamed/refactored the StationSummary methods, but I'm not sure how to fix it so posting this here.

**Comment by emthompson-usgs** [comment]
I believe getStationMetrics is deprecated, and has been replaced by getStreamMetrics:
https://github.com/usgs/groundmotion-processing/blob/37655de8e5bdf19852533f96f16712358098d8c7/gmprocess/io/asdf/stream_workspace.py#L691
@mhearne-usgs, can we delete getStationMetrics?

**Comment by mhearne-usgs** [comment]
Yes, we can.
