### ISSUE TITLE
python or pytest as executable for test scripts?

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#398]
@emthompson-usgs @mhearne-usgs I noticed that the test scripts are generally of the form

```
/usr/bin/env python

def test_func():
    return

if __name__ == '__main__':
    os.environ['CALLED_FROM_PYTEST'] = 'True'
    test_func()
```

Why is the `python` executable used instead of doing the following?

```
/usr/bin/env pytest

def test_func()
    return

if __name__ == '__main__':
    test_func()
````

This approach allows use of pytest fixtures and other features.

**Comment by mhearne-usgs** [comment]
@baagaard-usgs We didn't know that you could use the pytest executable in that way. Does that still allow a developer to run this in a debugger inside, say, ipython and set breakpoints and whatnot?

**Comment by mhearne-usgs** [comment]
@baagaard-usgs Ignore that last question, marked by me as stupid since if you run the test from ipython, *that* is your interpreter.

**Comment by baagaard-usgs** [comment]
Yes, you can interact with the debugger. My main concern was whether it would affect the CI stuff.

**Comment by mhearne-usgs** [comment]
I imagine that if you can run the tests on a laptop, you should be able to run on CI systems. Try one and see.

**Comment by baagaard-usgs** [comment]
PR https://github.com/usgs/groundmotion-processing/pull/400 passed the CI tests, confirming that /usr/bin/env pytest is compatible with the way it runs the test suite.
