### ISSUE TITLE
Add more readers

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/groundmotion-processing#4]
- [x] [SMC](https://escweb.wr.usgs.gov/nsmp-data/smcfmt.html)
- [ ] [BBF](https://escweb.wr.usgs.gov/nsmp-data/smcfmt.html)
- [ ] PNSN
- [x] USC (V1)
- [ ] USC (V2)
- [x] COSMOS (V1)
- [x] COSMOS (V2)
- [x] DMG (V1)
- [x] DMG (V2)
- [x] Kiknet/Knet

**Comment by mhearne-usgs** [comment]
DMG V1 addressed in PR#16

**Comment by hschovanec-usgs** [comment]
University of Chili format appears to be a form of [DMG](http://terremotos.ing.uchile.cl/).

**Comment by emthompson-usgs** [comment]
Closing this old issue. We can re-open for any specific new format requests.
