### ISSUE TITLE
conda install with Python 3.7 uses obspy 1.1.0, not 1.1.1

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#427]
Installing via conda using Python 3.7 results in obspy 1.1.0 being used instead of 1.1.1. This can cause test failures associated with obspy features such as phase pickers. This appears to be a result of some gmprocess dependencies not being updated with Python 3.7 versions. The solution is to use Python 3.6.

**Comment by emthompson-usgs** [comment]
This is no longer an issue.
