### ISSUE TITLE
Add command line option to output network table

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#435]
Add a command line option to get the table of the number of records by network that have passed processing checks. Include a column for number of records by network that have failed processing checks.

**Comment by baagaard-usgs** [comment]
I propose `--status` to show network table and failure status (This combines https://github.com/usgs/groundmotion-processing/issues/436, this issue, and https://github.com/usgs/groundmotion-processing/issues/327).

`--status=short` would lsit number passed and filed for each network. 
`--status=long` would give status for each station and failure reason if it failed.

It would be nice to have this functionality in the API, so I propose it be implemented in some function and then gmprocess simply calls that function as desired.

**Comment by emthompson-usgs** [comment]
The idea to make this available via the API is good. There might also be other existing functions that would benefit from being refactored like this. Also, the proposed command line arguments make sense to me, and closes #327. But issue #436 would be an even simpler representation than the proposed output of `--status=short` so I propose that we have three options:
- `status=short` two column table, columns are "failure reason" and "number of records";  number of rows is the number of unique failure reasons. 
- `status=net` three column table, columns are "network", "number passed", and "number failed"; number of rows is the number of unique networks. 
- `status=long` two column table, columns are "station id", "failure reason" (blank if passed). 

(closes #436)

**Comment by baagaard-usgs** [comment]
We need to add the description of this option to the documentation of `gmprocess`.
