### ISSUE TITLE
Align processing parameters with defined seis-prov "activities"

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/groundmotion-processing#47]
The seis-prov project defines a means to record processing steps performed on waveform data. These activities are defined here:

http://seismicdata.github.io/SEIS-PROV/_generated_details.html#activities

I believe we ought to align the names and parameters of the 'processing_parameters' dictionary in the Trace objects operated on in the process.py module to match those defined by the seis-prov project.

These parameters can then be encoded into ASDF files that we save - an ASDF module is in progress.

**Comment by emthompson-usgs** [comment]
Closing because I'm doing this as part of #49.
