### ISSUE TITLE
Plot regression fails with a non-IMT column

### ISSUE THREAD

**Issue by jrekoske-usgs** [usgs/groundmotion-processing#491]
**Describe the bug**
In `gmprocess`, the plot_regression can sometimes fail when it tries to use a column for the IMT which isn't actually an IMT, such as BackAzimuth or RuptureDistance. This could be fixed if the `NON_IMT_COLS` is updated to include all of the non-imt columns. Since we are likely to add additional non-imt columns to the flatfiles in the future another solution might be to directly specify the IMT that should be used for the plot.

**Comment by mhearne-usgs** [comment]
This was addressed in my most recent PR - the issue was that the plotting routine, which cannot assume which IMCs and IMTs may have been configured, looks first for *common* IMCs and IMTs. This list of common IMCs was capitalized, but the IMCs that have actually been generated are lower case.
