### ISSUE TITLE
SNR Check failing for certain ?N? stations (e.g. LN?).

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#517]
**Describe the bug**
When running gmprocess where channels are specified as ?N? for certain events, a ValueError is obtained stating that "zero-size array to reduction operation minimum which has no identity".

**To Reproduce**
1. Run gmprocess on event se60247871 with a config file specifying channels as ?N?
2. The error should result.

**Expected behavior**

**Screenshots**
![Screen Shot 2020-06-22 at 11 41 37 AM](https://user-images.githubusercontent.com/66430749/85318621-85fbba00-b47d-11ea-999b-6bebed1a750c.png)

**Environment (please complete the following information):**
 - gmprocess
 - Python Version 3.7

**Comment by emthompson-usgs** [comment]
We should exclude LN* stations using the config file.
