### ISSUE TITLE
Inconsistent use of Exception and GMProcessException

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#526]
The gmprocess code does not raise exceptions in a consistent manner. Some places raise `Exception` while others raise `GMProcessException`. We need a rationale for when to use `GMProcessException` or standard exceptions. Do we ever want to raise the standard exceptions `ValueError`, `IOError`, etc?

**Comment by emthompson-usgs** [comment]
Yes, this reflects a change in coding style that happened. We can/should discuss at the next meeting, but I don't like the use of GMProcessException. I think we should be using the standard exceptions where possible.

**Comment by mhearne-usgs** [comment]
As discussed, we should have one person go through the code and look for all instances of any type of Exception being raised. Bare Exceptions are a terrible idea, so this process should do the following:
1) Identify any use of Exception/GMProcessException
2) try to convert to one of the standard Python exceptions. Failing that, define a reasonable new exception that describes the problem. Perhaps categorize the error conditions we are seeing to narrow down the number of custom exceptions we create.
