### ISSUE TITLE
Refactor gmprocess script and top-level functions

### ISSUE THREAD

**Issue by baagaard-usgs** [usgs/groundmotion-processing#541]
I propose that we refactor the gmprocess script and top-level functions into a more object oriented organization. This will reduce the need to pass lots of arguments to functions and make it easier for users and new developers to follow the code. It would also facilitate alternative implementations and functionality (records versus synthetics, stations versus surface, etc). 

Possible reorganization:

* `ProcessingApp`: main application driver with one top-level function for each high-level step (e.g., `assemble()`, `process_waveforms()`, `compute_station_metrics()`, `compute_waveform_metrics()`).
* Consolidate code for each step into separate subdirectories and/or objects. Currently the assemble step (fetching, reading) is spread across several files and functions making it difficult to follow. It also makes it difficult to implement alternative assembly steps (e.g., assembling surface waveforms as opposed to station waveforms).

The `gmprocess` could be reduced to 

```
from gmprocess.apps import ProcessingApp

if __name__ == "__main__":
    ProcessingApp().main() 
```

**Comment by baagaard-usgs** [comment]
## Summary

* Try using [dask](https://dask.org/) for parallel processing. Backup plan is to use `multiprocessing` Python module which works on both Unix and Windows systems.
* Put processing steps into `coremods` as is done for [ShakeMap](https://github.com/usgs/shakemap).
* I separated the generation of the event information into separate modules, one for each way a set of events is specified.
* General style: Keep methods/functions short. Use objects to bundle functions sharing data and avoid passing more than a few arguments to functions.

## Questions

* It looks to me like ShakeMap breaks the config into separate files with hardwired names. Do we want to go that route or keep our current setup? I vote for the current setup.
* ShakeMap has a rather sophisticated logger setup. Do we want to go that route or use a single logger?

## Reorganize gmprocess directory

* **apps**: Directory containing high-level application objects
  - `processing.py` ProcessingApp
* **coremods**: One module per processing step
  * `assemble.py`
  * `process_waveforms.py`
  * `compute_station_metrics.py`
  * `compute_waveform_metrics.py`
  * `generate_report.py`
  * `export_flatfiles.py`
  * `export_shakemap.py`
* **utils**
* **events**: Directory containing modules for loading events via various ways
  - `comcat_ids.py` Config section contains a list of ComCat ids
  - `event_info.py` Config section contains a list of id,date/time,lat,lon,depth,mag,magType
  - `event_file.py` Config section contains name of text file with event info (same as eventinfo)
* **io**
* **assemble**: Code for 'assemble' step
* **station_metrics**
* **waveform_processing**
* **waveform_metrics**
* **report**
* **export**


## `bin/gmprocess`

```python
from gmprocess.apps import ProcessingApp

if __name__ == "__main__":
ProcessingApp().main()
```

## ProcessingApp

### Command line arguments

* Top-level
  - `--events-module=MODULE_PATH`
  - `--processing-tag=TAG`
  - `--show-status`
  - `--show-provenance`
* Processing steps
  - `assemble`
  - `process-waveforms` 
  - `compute-station-metrics`
  - `compute-waveform-metrics`
  - `export-flatfiles`
  - `export-shakemap`
  - `generate-report`
* Other
  - `--flatfile-format=FORMAT`
  - `--export-dir=DIR_PATH`
  - `--output-directory=DIR_PATH`
* Help/logging
  - `--help`
  - `--log=FILENAME`
  - `--debug`
  - `--version`

### Skeleton code

```python
from dask.distributed import Client

class ProcessingApp(BaseApp):

    def main(self, **kwargs):
        args = argparse.Namespace(**kwargs) if kwargs else self._parse_command_line()
        logger = self._create_logger(args)

        config = self._load_config(args.config)
        events = self._load_events(args.event_module)

        # I think this is the correct way to package things for parallel processing with dask
        client = Client()
        worker_args = [[event, args.cmds, config, logger] for event in events]
        futures = client.map(process_event, worker_args)
        client.gather(futures)

    @staticmethod
    def process_event(self, event, arg_cmds, config, logger):
        # This may have to be a top-level module function to
        # work. Dask documentation is not clear.
        
        # I strongly recommend breaking main() in bin/shake into
        # several methods/functions to keep them short and easy to
        # read. This is how I would have things at the top-level.

        # Need to set _classes_
        cdb = CommandDatabase(_classes_)
        try:
            commands = self._get_commands(arg_cmds)
            for command, obj in commands.items():
                logger.info('Running command {}'.format(command))
                obj.check_status(cdb)
                try:
                    # Pass whole config or only config section associated with command?
                    obj.execute(config, logger)
                except Exception as ex:
                    logger.warning('ProcessingApp terminated in module {}: {}'.format(
                        command, str(ex)))
                    break
        except Exception as ex:
            logger.critical(error_msg)
            sys.exit(1)
        logger.info('Finished processing event {}.'.format(event["id"]))

    def _parse_command_line(self):
        """Parse command line arguments.
        """
        parser = argparse.ArgumentParser()
        # STUFF GOES HERE
        return parser.parse_args()

    def _load_events(self, event_module):
        loader = importlib.import_module(event_module)

        # Need to get config info relevant for event module; pass down as arg to load_events?
        
        return loader.load_events()

    def _load_config(self, configs):
        # STUFF GOES HERE
        self.config = config

    @staticmethod
    def _get_commands(self, arg_cmds):
        commands = []
        # STUFF GOES HERE
        return commands
```

**Comment by baagaard-usgs** [comment]
Small updates to proposed reorganization:

1. Move primary data structures (stationstream, streamcollection, etc) to `core`.
2. Put processing step modules in `commands` instead of `coremods` to avoid confusion with `core`.

## Reorganize gmprocess directory


* **apps**: Directory containing high-level application objects
  - `processing.py` ProcessingApp
* **core**: Primary data structures
* **commands**: One module per processing step
  * `assemble.py`
  * `process_waveforms.py`
  * `compute_station_metrics.py`
  * `compute_waveform_metrics.py`
  * `generate_report.py`
  * `export_flatfiles.py`
  * `export_shakemap.py`
* **utils**
* **events**: Directory containing modules for loading events via various ways
  - `comcat_ids.py` Config section contains a list of ComCat ids
  - `event_info.py` Config section contains a list of id,date/time,lat,lon,depth,mag,magType
  - `event_file.py` Config section contains name of text file with event info (same as eventinfo)
* **io**
* **assemble**: Code for 'assemble' step
* **station_metrics**
* **waveform_processing**
* **waveform_metrics**
* **report**
* **export**

**Comment by jas82** [comment]
* Consolidate the code for each step into separate subdirectories and/or objects. Currently the `assemble` step (fetching, reading) is spread across several files and functions making it difficult to follow. It also makes it difficult to implement alternative assembly steps (e.g., assembling surface waveforms as opposed to station waveforms).

It might be tricky to cleanly separate `assemble`, but it I strongly agree with this idea.

* Try using [dask](https://dask.org/) for parallel processing. Backup plan is to use `multiprocessing` Python module which works on both Unix and Windows systems.

I like the idea of trying [dask](https://dask.org/). It look potentially easier to implement than mpi and is advertised as quite powerful (although it does add some overhead). It might also be worth trying xarray (http://xarray.pydata.org/en/stable/) if the data incorporates more than just ground motion time-series (gps, temperature, and such).

* It looks to me like ShakeMap breaks the config into separate files with hardwired names. Do we want to go that route or keep our current setup?

I like breaking the config files up into smaller files. The config file is already pretty large. I think shakemap has a nice way to accommodate a lot of options for configuration.

* Help/logging
    * --help

If a user wants to know how to do a specific thing (change the window selection for instance), --help could link to the documentation on the site. I think the --help output could be cleaner.

Overall, I think this reorganization looks good. 

Maybe the first priority should be reorganizing the gmprocess directory to make it easier for developers. Then try speeding it up with [dask](http://dask.org)?

**Comment by jas82** [comment]
My initial attempt to reorganize the **gmprocess** directory:

**apps** : ProcessingApp module
**coremods** Core modules and data structures. Meaty commands (assemble, process, metrics) should be in their own directory. Also can put core data structures here.
  * `assemble`
      - `assemble.py`
      - `fetcher.py`
      - `global_fetcher.py`
      - `fetch_utils.py`
  * `waveform_processing`
      - `process_waveforms.py`
      - `filtering.py`
      - `fft.py`
      - `spectrum.py`
      * `smoothing`
  * `waveform_metrics`
      - `compute_waveform_metrics.py`
      * `imp`
        - `arias.py`
        - `duration.py`
        - `fas.py`
        - `pga.py`
        - `pga.py`
        - `sa.py`
      * `imc`
        - `arithmetic_mean.py`
        - `geometric_mean.py`
        - `gmrotd.py`
        - `greater_of_twohorizontals.py`
        - `quadratic_mean.py`
        - `rotd.py`
  * `station_metrics` (More needs to be added)
      - `compute_station_metrics.py`
      - `station_summary.py`
  - `report.py`
  - `export.py`
  - `events.py`
**io** All reading and writing modules for data format and models
    - `asdf`
    - `bhrc`
    - `cosmos`
    - `cab`
    - `dmg`
    - `esm`
    - `genet`
    - `knet`
    - `nsmn`
    - `obspy`
    - `renadic`
    - `smc`
    - `unam`
    - `usc`
    - `read.py`
    - `read_directory.py`
    - `models.py`
    - `seedname.py`
**data** (should testdata be moved to a parent directory of gmprocess?)
      - `constants.py`
      - `config_test.yml`
      - `config_production.yml`
      - `fdsn_codes.csv` (and the rest of the csv and xlsx files)
**utils**
      - `args.py`
      - `exception.py`
      - `logging.py`
      - `plot.py`
      - `tables.py`
      - `utils.py`

Another option would be to put all the signal processing stuff (that is shared by multiple commands) in a separate place for shared modules (inside utils?).

**Comment by mhearne-usgs** [comment]
I think this plan is great. The only thing I would add is to note that it is possible to make subcommands with argparse, where each subcommand has it's own set of command line options. I don't know that this is needed, but know that it is an option.

Made up Example:
gmprocess assemble --japan-only --config=/tmp/config.yml process --ignore-errors...

This functionality is documented here:
https://docs.python.org/3/library/argparse.html#sub-commands

One of the other reasons to be excited about breaking up the functionality is that it might make it easier to make a parallelized version of gmprocess in the cloud, where we set up pipelines of lambda functions to handle each of these steps. @hschovanec-usgs and I have briefly discussed this and think it's an exciting possibility.

**Comment by emthompson-usgs** [comment]
If we needed some visual motivation to refactor, here's a diagram of the dependencies of our internal modules. The term "rats nest" comes to mind...
![gmprocess](https://user-images.githubusercontent.com/15928870/102799451-cb873a00-436f-11eb-96de-7badf23dc270.png)

**Comment by emthompson-usgs** [comment]
I'm getting ready to send in a first pass at this refactor. If you want to review how I'm doing this, please check my branch [here](https://github.com/emthompson-usgs/groundmotion-processing/tree/refactor). I haven't created a PR yet because I haven't written tests yet. A few things to note:
- I called the new command line program `gmp` for short. I also restricted my changes to not break the existing `gmprocess` command. But I renamed it to `gmprocess2` since I realized it is probably a bad idea to have a command line program with the same name as the main package. I think that things can be improved further if we abandon the gmprocess command. 
- I didn't make a `BaseApp` class for the apps to inherit from because I couldn't think of a reason for the base class. Perhaps when we make more apps the need for it may become apparent. Or you can expand on what it should do. 
- That said, I did make a subcommand base class that handles some basic things like ensuring certain properties are set in the subcommands, loading config info, and has some methods for code that is used in multiple subcommands. 
- I think that **ALL** of the command line tools (e.g., `gmconvert`, `gmworkspace`) can be moved to subcommands but I did not do that yet. Something for a future PR. 
- I added a subcommand `projects`. A "project" in gmprocess is very much like a "profile" in ShakeMap. Each project has a conf and data directory, and you can have multiple projects and switch between active projects. The main purpose is to prevent users from having to specify long paths at the command line and worry about specifying a conf file. 
- Since I'm using argparse subparser to manage the subcommands and their arguments, we can no longer chain subcommands. I think this is a good thing since that was getting cumbersome to manage. Note that subcommands also have short aliases to make the command line usage more concise. 
- What used to be `gmsetup` is now baked into the gmprocess projects. You create a project with `gmp projects -c` and the user then gets prompted to set the conf and data paths, as well as provide user name and email for provenance purposes.

**Comment by emthompson-usgs** [comment]
Closing this because I think the refactor is in good enough shape for now.
