### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#577]
This is an issue to keep track of remaining tasks for the documentation update. @jas82 and @baagaard-usgs, please let me know if I forgot anything.

 - [x] Build API docs (completed by @jas82)
 - [x] Configure build on readthedocs (completed by @jas82)
 - [x]  Debug build readthedocs issues
 - [x] Reorganize the documentation sections and content
 - [x] Update the build to get the correct version number
 - [x] Tweak the theme style
 - [x] Fix acknowledgements section
 - [ ] Fill in all sections (marked with a "TODO" admonition)
 - [ ] Add more tutorials
     - [x] Add example comparing response spectrum for a station to one or more OQ GMPEs.
     - [x] Add example computing ground motion residuals and computing mixed effects regression.
     - [ ] Demonstration of browsing workspace file to get processed streams and associated parameters, e.g., #697.
     - [ ] Demonstration of processing seismograms in parallel using DASK (might be useful for customization and number of cores/nodes if this is added as a command line flag later on)
     - [ ] A tutorial on reproducibility. If one user shares a dataset with another user that was produced/processed using gmprocess, it would be useful to know the exact OS environment and processing steps that were used for the dataset. I am picturing one user downloading/processing a dataset and then handing off that dataset to another user. This other user runs some command (or opens a text file) to know the exact environment and processing steps used for the dataset. This is useful for troubleshooting and reproducing code.
     - [ ] Using gmprocess with seismograms not fetched from its configure file. For instance simulation produced (bbp/cybershake) seismograms.

**Comment by emthompson-usgs** [comment]
I made some progress on this. You can view it here: 
https://gmprocess.readthedocs.io/en/latest/
A lot of the content is still outdated. But I think the biggest problem is that if you are in a section that is low on the navbar, navigation is horrendous. For example, right now if you go into the API and click on a module, the page reloads and so you go back to the top of the navbar. I think we need to think of some kind of adjustment to get around this.

**Comment by jas82** [comment]
I think that top bar looks really nice. The source code is not loading on some of the methods and yeah, the navigation is a bit weird on my browser. I think navigation works better for the api in this furo-based package: https://pradyunsg.me/furo/reference/api/

**Comment by emthompson-usgs** [comment]
Yeah, I haven't gone through the API in detail yet. First, I'm trying to reorganize the content/navigation, update it, and convert rst. I do think the "announcement" bar can be improved, but I decided to stop fussing with it because I'm not that good with css. The title text isn't aligned vertically, and there's a weird gray bar on the right margin and I haven't been able to figure out how to get rid of it.

**Comment by jas82** [comment]
I had a few thoughts for possible tutorials to add to the docs:

- Demonstration of processing seismograms in parallel using DASK (might be useful for customization and number of cores/nodes if this is added as a command line flag later on)
- Some features on reproducibility. I think it could be useful to reveal the processing steps/library versions/OS, etc. and so on if a dataset is shared between different users.
- Using gmprocess with seismograms not fetched from its configure file. For instance simulation produced (bbp/cybershake) files or seismograms from NGA database.

**Comment by emthompson-usgs** [comment]
These are all good ideas. I just am running out of time I can spend on the docs so we may need others to start contributing. The NGA waveforms are not publicly available and so we can't do that, but we should add an example where we download the waveforms for events and compare to their response spectra.

**Comment by emthompson-usgs** [comment]
@jas82 I added your suggestions to the checklist in my original comment. Feel free to edit it if you have other ideas. Note, I'm not 100% clear on what you are envisioning for the reproducibility one, so it might be helpful for you to edit/expand that one in particular.
