### ISSUE TITLE
Error in tstream reading

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#600]
Once you have established the `conf` and `data` directory paths for the project, run the following:
`$ gmrecords download -e nm608769`

This is the resulting error:

![Here](https://user-images.githubusercontent.com/66430749/104387367-28e85400-54f4-11eb-9cee-dfe597c87e67.png)

I believe placing [this portion of the code](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/io/obspy/fdsn_fetcher.py#L292-L295) into the "try" statement would work, but I can take a look at what is going on here. Perhaps defining `tstreams = None` in the except statement would suffice.

**Comment by emthompson-usgs** [comment]
Thanks @dchurchwell-usgs, I will fix this as soon as I can. In the future, please include error messages as copy/pasted (into a block surrounded by triple back quotes) text rather than images. Like this:
```
raise Exception("Use text rather than images.")
```

**Comment by emthompson-usgs** [comment]
@dchurchwell-usgs I believe that PR #601 will fix this. Please update the code, rerun and let me know. Thanks.

**Comment by dchurchwell-usgs** [comment]
No problem. I will have tha practice going forward. 

Regarding PR #601, the change fixes this issue.

**Comment by emthompson-usgs** [comment]
@dchurchwell-usgs Actually, it occurs to me that I should have put that inside the except block, as you suggested. I wasn't thinking. Also, since this part of the code isn't getting touched by our unit tests, could you make as minimal an example as possible with this data and create a unit test out of it?

**Comment by dchurchwell-usgs** [comment]
@emthompson-usgs sure thing! I'll get started on that.
