### ISSUE TITLE
Encoding issue in CESMD searcher

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#605]
There is a problem trying to encode an argument in binary mode when trying to search for CESMD data of a particular event. Other events did not have this problem when searching for data.

After initializing a project *and* inputing a registered email into the CESMD portion of the config file, run the following:

```$ gmrecords download -e nm608509```

The following error will result at [this point in the code](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/io/cosmos/cesmd_search.py#L445) in the CESMD section:

```ValueError: binary mode doesn't take an encoding argument ```

Looking on the CESMD website, I cannot seem to find the event anywhere. Potentially that is causing this issue?

**Comment by emthompson-usgs** [comment]
Closed by #614. Thanks @arkottke!
