### ISSUE TITLE
Index error in making reports

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#611]
When making reports, an index error occurs when searching for processed streams for the event. There is no processed waveform data for this particular event. 

To reproduce:

- Get to a point where you are able to make a report for event `usp000jar2`(I.e. download data, assemble data, and then process data).
- run `gmrecords report -e usp000jar2
- The following error will result at [this point in the code](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/subcommands/base.py#L90) `IndexError: list index out of range`

From running `gmrecords download`, data waas downloaded from three stations, but I guess none of it was processed after running `gmrecords process -e usp000jar2`. Figuring out how to put events like that into the report seems to be the issue.

**Comment by emthompson-usgs** [comment]
Thanks @dchurchwell-usgs. I'll take a look at this.

**Comment by emthompson-usgs** [comment]
The downloaded data are all LN channels, which we intend to exclude from the NDSN query. So there are (at least) two bugs: 1) Why are we even getting the data? and 2) When we have data but it doesn't get processed (and in this case it shouldn't) we shouldn't get an exception.

**Comment by emthompson-usgs** [comment]
I see now. The exclude_pattern can't be applied to the FDSN query, so we use it later. That's too bad. We should maybe think of changing the section where this is defined, but let's leave that for when we do a redo the config.
