### ISSUE TITLE
Provide both an upper and lower limit to the number of traces

### ISSUE THREAD

**Issue by arkottke** [usgs/groundmotion-processing#612]
**Is your feature request related to a problem? Please describe.**
Downloaded data from SH* instruments includes stations with only vertical. No mechanism to exclude this data. Perhaps I shouldn't be working with this data?

**Describe the solution you'd like**

There are two options: 
1) Refactor `gmprocess.waveform_processing.processing.max_traces` to have both an upper and lower limit
2) Add a `min_traces` processing step.

Option (1) seems cleaner. I have currently implemented Option (2) because it was easier and didn't change the configuration format.

**Comment by emthompson-usgs** [comment]
I'm tempted to replace `max_traces` with a `n_trace_limit` step, having arguments for min and max. But I think that for the case you are describing, you actually want a minimum number of *horizontal* component traces. So that makes me think a solution like option 2 would be best, but modified to only count horizontal components. Let me know if you agree.

**Comment by arkottke** [comment]
What about replacing `max_traces` with a `check_instrument` function that has the following arguments:
- n_max (default: 3)
- n_min (default: 1)
- require_two_horiz_components (default: False)
This would combine all of the testing of the instrumentation into one function and solve all of these issues.

**Comment by emthompson-usgs** [comment]
This sounds like a solid plan. I'll keep the current `max_traces` step and mark it deprecated to avoid breaking anyone's existing workflow. Can you send me example raw data for one of the SH* instrument that motivated this for me to use for unit testing purposes?

**Comment by arkottke** [comment]
Here you go. I can implement the function.

![image](https://user-images.githubusercontent.com/1033651/105394145-121bbe80-5bd2-11eb-9238-f1047b9ede60.png)

[nc51194936.tar.gz](https://github.com/usgs/groundmotion-processing/files/5851320/nc51194936.tar.gz)

**Comment by emthompson-usgs** [comment]
Great, thanks! If you want to add the function and not deal with the unit test, I'll be happy to add the unit test.

**Comment by arkottke** [comment]
Eric, I created a pull request without a test case (which isn't the best practice). Is there a reason that that test data isn't stored in the test directory?

**Comment by emthompson-usgs** [comment]
I think we decided to put the data into `gmprocess/data/testdata` because it is easier to load for tutorials and stuff like that. I think there were issues with accessing any data that is outside of the base package directory.

**Comment by emthompson-usgs** [comment]
I just made an issue to do the unit test. If you don't have time, I'll do it. 
https://github.com/usgs/groundmotion-processing/issues/623
