### ISSUE TITLE
Error in reading CESMD data with Flags

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#648]
Problem flag is present in a record downloaded from CESMD database.

**To Recreate:**

1. initialize a project and input a registered email into the CESMD section of the default config file. Set the radius of station searching to be 500km. This will allow for the retrieval of CESMD data.
2. Run `gmrecords download -e us20009wba`
3. Run `gmrecords assemble`
4. You'll receive the following exception: `BaseException: SMC: Record found in file /var/folders/57/_5l4zrw13y92sjj_kc7tcf1r002lg6/T/tmpywcjtap6/directory_to_streams/StroudOklahoma_14Jul2017_20009wba_StroudOklahoma_14Jul2017_20009wba_NP2478_stroudoklahoma_14jul2017_20009wba_np2478r_2478.HNZ.NP.01_u.smc has a problem flag!`

Not sure what the flag is, but perhaps this might be a CESMD thing? I am not sure.

**Comment by dchurchwell-usgs** [comment]
Just saw that this is the same issue referenced in #639 . Not sure if I should close this issue or leave it open at this point.

**Comment by emthompson-usgs** [comment]
Leave this open. The other issue is actually separate. I'll take care of this. It looks like an exception is getting raised but we should just be failing the record and moving on.
