### ISSUE TITLE
Wrap subcommands in easily-callable functions

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#652]
The idea is to easily call the subcommands in other python scripts. The tricky part will be to figure out how to handle the argparse object, and instead allow the command line arguments to be specified as method arguments.

**Comment by baagaard-usgs** [comment]
This is what I use in my application objects. When I call `main()` from a script, I pass kwargs as a `dict`.

```Python
    def main(self, **kwargs):
        """Main entry point
        """
        args = argparse.Namespace(**kwargs) if kwargs else self._parse_command_line()
        # ...

    def _parse_command_line(self):
        """Parse command line arguments.
        """
        parser = argparse.ArgumentParser()
        # parser.add_argument(...)
        return parser.parse_args()
```

**Comment by emthompson-usgs** [comment]
@baagaard-usgs I think that due to the way `gmrecords` handles the config file, command line arguments for itself and the subcommands, it is pretty convenient to simply create a `gmrecords` instance and then hand it off the subcommands. I created a "meta" program that is meant for processing events for ShakeMap [here](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/subcommands/auto_shakemap.py), and it basically does what I am describing. Please let me know if you think this is sufficient or if there's a need for different behavior. 

@arkottke I think something like this would also be helpful for you, since you were saying that it would be nice to not have to run each subcommand every time. It should be pretty easy to make custom "meta" commands like this for different use cases.

**Comment by baagaard-usgs** [comment]
The meta program approach looks good!

**Comment by emthompson-usgs** [comment]
Okay, thanks. I'll close this issue then.
