### ISSUE TITLE
AR Picker Failing

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#655]
When processing data, the AR picker is failing at [this point in the code.](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/waveform_processing/phase.py#L268)

TO REPRODUCE: 
- Set config to take in CESMD data with radius of 500km
- download, assemble, and process data for event `nm609799`
- The following results: `BaseException: Unable to perform AR picker.`

Perhaps this is fixed by attempting to do this and then pass over it if this process fails.

**Comment by emthompson-usgs** [comment]
@dchurchwell-usgs Are you sure you are getting the data with the CESMD fetcher? Do you also have the FDSN fetcher configured?

**Comment by dchurchwell-usgs** [comment]
I did also have the FDSN fetcher configured as well (deg=5). I should have specified that above. It seems that the specific station that is failing is `NM.TUMT.NQ.HNZ` and it comes from the FDSN fetcher.
