### ISSUE TITLE
Discuss subclassing obspy trace class

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#66]
Main issue is that we need to keep track of some additional attributes. We've written some setters/getters to help manage those. Might make sense for those to be class methods.

**Comment by jmfee-usgs** [comment]
@emthompson-usgs : in geomag-algorithms we've been adding custom properties to the obspy Stats object, which is attached to the Trace.

**Comment by emthompson-usgs** [comment]
@jmfee-usgs Sounds like that is what we are currently doing. It is just getting so that the structures were are putting there might be getting complicated enough that it would be useful to have some helper functions and those helper functions might be most convenient as class methods.
