### ISSUE TITLE
KeyError when initializing a new project

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#670]
When attempting to create a new project, I receive a key error for 'project'. 

TO REPRODUCE:
1. Create a new directory or navigate to a directory that is not already associated with a project.
2. run `gmrecords init`
3. The following will result: `KeyError: 'project'` at [this point in the code.](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/utils/config.py#L82)

I'm guessing that changes to a certain dependency or where a project element is added to the variable will resolve this. Not sure exactly where it should go, though.

**Comment by emthompson-usgs** [comment]
Closed by #672.
