### ISSUE TITLE
Specify temp directory in the project configuration

### ISSUE THREAD

**Issue by arkottke** [usgs/groundmotion-processing#687]
**Is your feature request related to a problem? Please describe.**

In [`read_directory`](https://github.com/usgs/groundmotion-processing/blob/b610dea8bfbc02dffaddffa218bc1d15f2fa8aa7/gmprocess/io/read_directory.py#L43), the `tempfile.mkdtemp()` command creates a directory in `tmp/`. When running on the TACC computers, `tmp/` filled up when I ran simultaneous processing.

**Describe the solution you'd like**
The two ideas I had were:
1) Specify the location of the temp directory in the project configuration.
2) Use at parent directory, which keeps everything on the same device. This is the solution I implemented because it was quick and easy:
```python
temp_dir = os.path.join(tempfile.mkdtemp(dir=directory), 'directory_to_streams')
```

**Comment by emthompson-usgs** [comment]
Like your second solution best because it seems simpler from a users perspective. Do you mind contributing this change? If not, I can do it.

**Comment by arkottke** [comment]
No problem.
