### ISSUE TITLE
NoneType Error in global fetcher when CESMD is Active

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#689]
When I am downloading data, the global fetcher errors out with `streams` being a `NoneType`, although the FDSN fetcher is still downloading data. 

**To Reproduce:**

1. Run `gmrecords download -e uu60363602
2. The following will result at [this point in the code:](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/io/global_fetcher.py#L88) `TypeError: object of type 'NoneType' has no len()`

Not sure if the `streams` variable is just getting overwritten somewhere, but it is strange that the type is None even though data is getting picked up from the FDSN fetcher.

**Comment by jas82** [comment]
I was not able to reproduce this bug.

**Comment by dchurchwell-usgs** [comment]
Ok. I'll try a reinstall and see if I run into problems again...Not sure why this would work though since I just did another reinstall a few days ago.

**Comment by dchurchwell-usgs** [comment]
Ok, updated methodology to reproduce (possibly)...

**To Reproduce:**

1. initialize a project. Change `config.yml` to allow for CESMD data to be downloaded at a with station radius set to 200.
2. Run `gmrecords download -e uu60363602`
3. The following will result at [this point in the code:](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/io/global_fetcher.py#L88) `TypeError: object of type 'NoneType' has no len()`

**Comment by emthompson-usgs** [comment]
We should probably always be handling if streams is None properly, regardless of the fetcher and we aren't right now. I'll fix this.

**Comment by emthompson-usgs** [comment]
@dchurchwell-usgs Please check when this PR gets merged and let me know if it resolves this issue for you: https://github.com/usgs/groundmotion-processing/pull/690

**Comment by dchurchwell-usgs** [comment]
@emthompson-usgs This fixed the problem.
