### ISSUE TITLE
ValueError errors out when computing station metrics of event with no data.

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#691]
I thought this was already addressed with an earlier pull request...I have not had this problem again until now. Maybe this portion of the code did not get updated with the pull request?

**To Reproduce**

1. download, assemble and process data for event `us2000ac81`. There should be no data after this step.
2. run `gmrecords compute_station_metrics -e us2000ac81`
3. The following will result at [this point in the code:](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/subcommands/compute_station_metrics.py#L262) `ValueError: zero-size array to reduction operation minimum which has no identity`

The code seems to run correctly in the sense that no data being present means that there should be no computations for station metrics. However, not erroring out would be nice when running a processing regime for a list of events.

**Comment by emthompson-usgs** [comment]
Thanks for reporting this. I agree that I thought we should have already taken care of this. The behavior when there's no data seems to be surprisingly complicated!

**Comment by emthompson-usgs** [comment]
I cannot reproduce this error. Are you sure you have updated code? Please send 
```
gmrecords -v
```

**Comment by dchurchwell-usgs** [comment]
gmrecords 1.0.5.dev426+gc9ff321.d20210324

**Comment by emthompson-usgs** [comment]
This looks like an issue that is related to when the event id is specified as a text file. I don't use this mechanism myself and so I think I messed it up when I refactored the code.
