### ISSUE TITLE
US.DUG.20.HN should not pass its report

### ISSUE THREAD

**Issue by ghost** [usgs/groundmotion-processing#698]
**Describe the bug**
For eventid uu60363757, site US.DUG.20.HN is passing its report, when it should fail its report.

**To Reproduce**
0. Change config file to only acquire high-gain for FDSN fetcher: (ie channels : ["HH?", "HN?"]). Also all networks except for 'US' for smaller download.
1. gmrecords download -e uu60363757
2. gmrecords assemble
3. gmrecords process
4. gmrecords report

**Expected behavior**
Station DUG should fail the SN criteria for all three components

**Screenshots**
![uu60363757_US DUG HN](https://user-images.githubusercontent.com/64432767/114924598-673f2900-9deb-11eb-962d-845cb8c90562.png)

**Environmnet**
 - macOS
 - -python 3.8.8

**Additional context**
![US DUG HN](https://user-images.githubusercontent.com/64432767/114925279-23005880-9dec-11eb-8989-2cae8daa54d5.png)

The trace starttime suggests that the instrument was not recording until well after the event origin time (and the P phase).
Event origin time: 2020-03-18T13:48:01.210000Z
Instrument start time: 2020-03-18T13:48:43.490001Z

**Comment by emthompson-usgs** [comment]
Sorry to not have gotten to this sooner. Here is this record reprocessed with the current code. As you can see, it no longer passes the QA tests so I'm going to close this issue. 
![uu60363757_US DUG HN](https://user-images.githubusercontent.com/15928870/140599543-c9ccd85a-f143-4bfa-ac02-8e15ac4c2231.png)
