### ISSUE TITLE
parallel processes errors for station/waveform metrics computations

### ISSUE THREAD

**Issue by jcy-go** [usgs/groundmotion-processing#704]
**Errors with parallel processing**
An error message was received when I try to compute station/waveform metrics only with parallel process. It is no issue on my end to process/assemble the ground motions with parallel processes. 

**To Reproduce: station metrics computations**
The command I ran for station metrics computations:
> gmrecords compute_station_metrics -t F:\gmprocess_projects\eventsID\June-Part1\events_p0.txt -l processed -n 10

The txt file **_events_p0.txt_** includes 10 event ID from ANSS Comcat. 

The screenshot of the error messages I received:
![1](https://user-images.githubusercontent.com/32785330/121823558-f47bee00-cc73-11eb-85e1-fe34f63b4722.PNG)

I re-ran the command with event ci39339191 without parallel processes. The command is as below:
> gmrecords compute_station_metrics -e ci39339191 -l processed  
There is no error and everything is fine.

When I tried to run the command with parallel process again (the command is below), the error message is a little different. The screenshot below is the corresponding bug information. 
> gmrecords compute_station_metrics -t F:\gmprocess_projects\eventsID\June-Part1\events_p0.txt -l processed -o -n 8

![2](https://user-images.githubusercontent.com/32785330/121823677-d5ca2700-cc74-11eb-81d3-52895b91cffe.PNG)

Before I started to compute station and waveform metrics, I entered the following commands. 

1. gmrecords proj -c
2. gmrecords download -t F:\gmprocess_projects\eventsID\June-Part1\events_p0.txt  
2. gmrecords assemble -t F:\gmprocess_projects\eventsID\June-Part1\events_p0.txt -n 6 
3.  gmrecords process -t F:\gmprocess_projects\eventsID\June-Part1\events_p0.txt -l processed -n 12  
4. gmrecords report -t F:\gmprocess_projects\eventsID\June-Part1\events_p0.txt      

**Expected behavior**
I was wondering if there are some problems on my end with the environment setting. Or is it an issue for windows OS? Thanks for your help. 

**Environmnet:**
 - OS: windows 10 education, version 1909
 - Python Version: 3.7.10
- Libcomcat Version: 2.0.10
- Numpy Version: 1.20.3

**Comment by arkottke** [comment]
I have had issues with the parallel processing as well. I got around the issue by specifying specific events IDs with the `-e` argument, and then doing parallel processing with [GNU parallel](https://www.gnu.org/software/parallel/). However, it would be good to improve this aspect of the code.

**Comment by emthompson-usgs** [comment]
@jcy-go @arkottke 
I was hoping to fix this today but haven't been able to figure out it. I can reproduce the problem, and the weird thing is that the error is indicating that there is no `dataset` attribute of `self` in `getStreams`, but within the function there are other references to `self.dataset` that do not raise an exception and so it is not clear to me how it is possible to get this error.

**Comment by emthompson-usgs** [comment]
@jcy-go @arkottke 
I hope that the changes I've made in #765 will resolve this issue.
