### ISSUE TITLE
A few ideas for improvement of the code.

### ISSUE THREAD

**Issue by arkottke** [usgs/groundmotion-processing#707]
I finally got around to using this code a little more and was able to use it to fetch and process a significant number of events. From this experience, I had a few idea of modifications and improvements.

1. The `conf/config.yml` uses absolute paths. This causes problems for clusters that might have a working disk space and a storage disk space. **Suggestion**: Change to using relative paths here, and expand them from the location of `config.yml`.
2. During the metric processing, lists are used to load all of the waveforms and store all of the processed results. For some events, storing all of the data requires a lot of RAM. The maximum that I saw was about 3 GB, but would increase for metrics with more points. (3 GB isn't very much, but that's a lot per process/core). **Suggestion**: Use iterators to loop over the wave forms and save the results as they are computed.
3. The dependency tree is vast. Just to read the h5 files that are produced requires a 2 GB conda environment. **Suggestion**: Add optional dependencies that are only needed for the actual processing.

**Comment by baagaard-usgs** [comment]
These all look like issues that we should address. Can you break this up into separate issues with appropriate descriptions? This makes it easier to see what needs to be done and track progress.

**Comment by arkottke** [comment]
Created #709, #710, #711
