### ISSUE TITLE
Relative paths in config.yml

### ISSUE THREAD

**Issue by arkottke** [usgs/groundmotion-processing#709]
**Is your feature request related to a problem? Please describe.**

The `conf/config.yml` uses absolute paths. This causes problems for clusters that might have a working disk space and a storage disk space. 

**Describe the solution you'd like**
Change to using relative paths here, and expand them from the location of `config.yml`.

**Describe alternatives you've considered**
I also like the idea of specifying the configuration file explicitly as part of running `gmrecords`, but I assume there are good reasons for using the current system.

**Comment by emthompson-usgs** [comment]
I'm a little confused and maybe problem is that we have multiple conf files. The `conf/conf.yml` conf file doesn't have any paths that I can find. Let me know if I'm missing something. 

I suspect that you meant the `.gmprocess/projects.conf` conf file that specifies the projects and the associated `conf_path` and `data_path`.

**Comment by arkottke** [comment]
Yes, I meant to say the `project.conf` file. Does that fit with your
workflow?

**Comment by baagaard-usgs** [comment]
Regarding this comment in the `projects` subcommand documentation:

> Within the `projects.conf` file, the key `project` indicates which the currently selected project. Multiple projects can be included in a `projects.conf` file, but that doesn't make a lot of sense for a "directory" type project.

Actually, I find it makes a lot of sense to have multiple projects within a local 'projects' directory. It is not uncommon for me to have a research project that involves processing multiple ground-motion datasets. I create a separate gmprocess 'project' for each dataset. Another use case is when a user wants to put all processed ground-motions under a directory that is on another filesystem separate from a home directory.

**Comment by emthompson-usgs** [comment]
Okay, I'll remove that in a new PR. It is unnecessary editorializing anyway.
