### ISSUE TITLE
Use iterators when accessing the workspace

### ISSUE THREAD

**Issue by arkottke** [usgs/groundmotion-processing#710]
**Is your feature request related to a problem? Please describe.**
During the metric processing, lists are used to load all of the waveforms and store all of the processed results. For some events, storing all of the data requires a lot of RAM. The maximum that I saw was about 3 GB, but would increase for metrics with more points. (3 GB isn't very much, but that's a lot per process/core).

**Describe the solution you'd like**
Use iterators to loop over the wave forms and save the results as they are computed.

**Describe alternatives you've considered**
If `dask` is more fully embraced this would also be resolved, but this would require a more extensive effort.

**Comment by emthompson-usgs** [comment]
Sorry, I don't really follow this. Can you point me to the part of the code where you are suggesting we replace lists with iterators?

**Comment by emthompson-usgs** [comment]
I think I see now, and clearly it is not useful to load all the streams if we are going to hand them off to separate processes. As a first step, I'll factor out the part where we construct/load the full list of streams. I'll have it iterate over the waveforms, and load only the stream for that waveform within the loop.

**Comment by emthompson-usgs** [comment]
While I haven't done exactly what this issue requests, I think the changes in #765 get pretty close.
