### ISSUE TITLE
CESMD data not being downloaded.

### ISSUE THREAD

**Issue by abinder2021** [usgs/groundmotion-processing#712]
**Describe the bug**
Certain events that appear to have data on the CESMD database online (Example: https://www.strongmotioncenter.org/cgi-bin/CESMD/iqr_dist_DM2.pl?IQRID=AmberleyNewZealand_13Nov2016_us1000778i&SFlag=0&Flag=2) are not downloading on gmprocess. When you download data for this event there is plenty of data being obtained from the global fetcher, but none of it is CESMD data. 

Other events that appear to have data on CESMD online, but do not get downloaded with gmprocess:
-usc000nzvd (Iquique, Chile, 4/1/2014)
-us20002926 (Gorkha, Nepal, 4/25/2015)
-us20002ejl (Nepal,5/12/2015)
-us20003k7a (Illapel, Chile,9/16/2015)
-us10006g7d (Amatrice, Italy, 8/24/2016)
-us1000731j (Norcia, Italy, 10/30/2016)
-us1000778i (example from above) (South Island, New Zealand, 11/13/2016)
-us10007mn3 (Quellon, Chile, 12/25/2016)

**To Reproduce**
1. Update config file to allow CESMD data to be obtained.
            a.   CESMDFetcher:
                      email: abinder@usgs.gov
                      eq_dt: 10
                      eq_radius: 10
                      process_type: raw
                      station_radius: 100
                      station_type: Ground
                  FDSNFetcher:
                      channels:
                      - "BH?"
                      - "HH?"                   #Used these channels to improve station search.
                      - "BN?"
                      - "HN?"

2. Download event 'us1000778i' (South Island, New Zealand) using gmrecords download -e us1000778i
3. Once finished downloading, analyze the /data/us1000778i/raw folder. Notice there is no CESMD data.

**Expected behavior**
When downloading, I expect to see CESMD data in the raw file along with the global fetcher data.

**Screenshots**
Only applicable screenshot would be a picture of my raw data folder without CESMD data. 

**Environmnet (please complete the following information):**
 - OS: [e.g. macOS]
 - Python Version [e.g. 3.6]
- Libcomcat Version [e.g. 1.0]
- Numpy Version [e.g. 1.17]

**Additional context**

I also have an issue with the Turkey fetcher not obtaining data. I tried this event from Van, Turkey, 2011: usp000j9rr and the turkey fetcher did not activate. Not sure why this is. Just something to note for future events.

**Comment by jas82** [comment]
@abinder2021 

I did not write the code for the CEMSD fetcher, but there are hard-coded bounds for the valid latitude and longitude in the CEMSD fetcher file:

groundmotion-processing/gmprocess/io/cosmos/cesmd_fetcher.py

If I modify these bounds (ie set xmin =-180, xmax=180, ymin=-90,ymax=90), then CEMSD will fetch the raw data for the New Zealand event: us1000778i

The original values will not allow the fetcher to retrieve this event because it will fail this if statement:

   if (xmin < lon < xmax) and (ymin < lat < ymax):
            instances.append(fetchinst)

I can go into more detail if you like, or just take a look at what the code is doing

I did not try this on the other event or on the Turkey fetcher, but I imagine this is the issue. I am thinking that these limits should be modified to cover the global range of lat/lon, unless I am missing somthing about the CEMSD fetcher and its uses (maybe there are dangerous if there are large requests that will not be healthy for the servers).

If this fix, works for you please let someone know and this bug report can be closed hopefully.

**Comment by emthompson-usgs** [comment]
@jas82 Thanks for looking into this! @abinder2021 Please confirm if this is the problem. I think that when @mhearne-usgs wrote this, we were expecting to get New Zealand data from Geonet. The solution here might be to update your config to use the geonet fetcher, but it is a good point that CESMD provides data for regions outside of California.

**Comment by abinder2021** [comment]
Great! I edited the lat/lon min/max values in the cesmd_fetcher.py and redownloaded all the events where I was experiencing this problem, and I was retrieving cesmd data unlike before! Thank you for helping me resolve this problem I was having.

From: Eric Thompson ***@***.***>
Date: Monday, August 2, 2021 at 6:57 PM
To: usgs/groundmotion-processing ***@***.***>
Cc: Binder, Alec C ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [usgs/groundmotion-processing] CESMD data not being downloaded. (#712)



 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@jas82<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjas82&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769882518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E7NmAw9E7hAtgJR4L%2Bgb3GTYFyPKH%2Bj9gjbjDlZbERI%3D&reserved=0> Thanks for looking into this! @abinder2021<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabinder2021&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769892478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cMURPGNbOAG%2Fb%2Fcs4%2BT5O3NFJW97rU6y0us8BdhMj%2FE%3D&reserved=0> Please confirm if this is the problem. I think that when @mhearne-usgs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmhearne-usgs&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769892478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zdaxi7s8oepHdk741s7rxEbRhfq6b8BkySAQ9sGWgno%3D&reserved=0> wrote this, we were expecting to get New Zealand data from Geonet. The solution here might be to update your config to use the geonet fetcher, but it is a good point that CESMD provides data for regions outside of California.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusgs%2Fgroundmotion-processing%2Fissues%2F712%23issuecomment-891428888&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769902431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PQbbMdFkxUmDgHJrR9BF%2FGZGFEGJx5WzLNCENd9WFGM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUP2DNCGS5FXPKE2MRIGMZTT245HZANCNFSM5BNG53EQ&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769902431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5iCWI36AvkPeDXBzinyxdhBZvJbI%2BtcJpFwGkNrtq%2B0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769912389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yPURAonuu41tX5%2F7i%2Fd7kVDfJ8UPr4GmuCY%2FdJaul0o%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cabinder%40usgs.gov%7C0939d218bb3943f271a508d95619ba43%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637635490769912389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GWThML8%2BGoI03E%2FVV02Knh678OHpfYUVsFZ%2FOO3VHdo%3D&reserved=0>.

**Comment by jas82** [comment]
@abinder2021  Glad to know I was useful. I will go ahead and close this issue.
