### ISSUE TITLE
Subclass obspy trace

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#74]

**Comment by baagaard-usgs** [comment]
If this subclass is meant to include station metadata (inventory) and the waveform trace, then how about naming it something like StationTrace so that the name indicates why it is more than just a trace.

**Comment by emthompson-usgs** [comment]
We had a discussion about this yesterday and arrived at the term "InventoryTrace" for similar reasons. Both make sense to me and I think I slightly prefer StationTrace now that you have suggested it. @mhearne-usgs is working on the initial Trace subclass implementation and so hopefully he doesn't mind this alternative name. We also realized that inventory data more naturally fits at the Stream level (there is a 1:1 mapping between station and the inventory, and multiple channels per station are grouped as Streams). So we think we need to also have a InventoryStream (or StationStream) subclass, which enforces validation rules like all traces in the stream have the same network and station code (also start times and end times; maybe more). And since we are now in the business of defining new classes to hold these things, we also realized that we are often working with a list of Streams and that it could be useful to define a StreamCollection (or StationStreamCollection) class that is defined as a list of StationStreams that will enforce some validation rules and have some useful class methods.

**Comment by baagaard-usgs** [comment]
`StationStream` or `InventoryStream` are both fine with me. `StationStream` is more consistent with the terminology we use outside of ObsPy (StationXML), whereas `InventoryStream` is more consistent with ObsPy terminology. I lean towards `StationStream` because it has more universal meaning than `InventoryStream`.

**Comment by emthompson-usgs** [comment]
Closed by PR #85.
