### ISSUE TITLE
Option to pull StationXML data from a specific directory

### ISSUE THREAD

**Issue by NNovoa-CDWR** [usgs/groundmotion-processing#740]
I was just wondering if it would be possible to add an option to pull StationXML data from a specified directory rather than saving xml files in each event directory?

**Comment by NNovoa-CDWR** [comment]
Not critical, but useful if you don't use the gmrecords download command. Example would be, you already have your data files on your machine locally sorted by event (either from past projects or, in our case, we are collecting our own data and it isn't posted to public data server) and all of your StationXML files are already in an existing library folder used by our collection software (e.g. Earthworm). Just saves a step from copying all of our StationXML files to the event folders. I would think it would also be useful if you are repeatedly looking at the same stations, not to have numerous copies of the same file.

**Comment by emthompson-usgs** [comment]
I don't think we need a large sample size. Maybe on the order of 2 events and 5 stations, in which at least one station had has a different metadata epoch for the two events. 

I'll update the docs as you requested, but I also intend to have the issue resolved asap.
