### ISSUE TITLE
Regression Plot Fails when PGA and PGV not Present

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#801]
Some config files may ignore PGA and PGV and have SA metrics. We expect, in this scenario, for the regression plot produced from ``gmrecords regression`` to plot SA(1.0) values. However, we get a key error instead: ``KeyError: 'default_default_fit_spectra_parameters'``

The problem is [here.](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/subcommands/generate_regression_plot.py#L112)

**To reproduce**
Run the following commands _with PGA and PGV removed from the config file_:

- ``gmrecords download -e se609212``
- ``gmrecords assemble``
- ``gmrecords process``
- ``gmrecords sm``
- ``gmrecords wm``
- ``gmrecords mtables``
- ``gmrecords regression``

At this point, you should receive the key error identified above.

**Comment by emthompson-usgs** [comment]
Closed by #802.
