### ISSUE TITLE
stream is labelle as "failed" 

### ISSUE THREAD

**Issue by hadigh** [usgs/groundmotion-processing#803]
**Describe the bug**

the Stream is labeled as "Failed" even though there are traces within Stream that "pass"; this prevents the "passed" traced to be processed by the code!  

**To Reproduce**
I have attached the input file to this message. in this case, BHE, and BHZ traces are passed but the stream is labeled as "failed" due to the failure of the BHN channel. (the results can be produced using a general config file generated by the program)

**Expected behavior**
Ideally, each trace that passes the criteria should be processed and ground-motion parameters should be computed for them. 

**Environment (please complete the following information):**

OS: Ubuntu 18.04
Python Version 3.8.6
Libcomcat Version 2.0.13
Numpy Version 1.21.4

[20000925155013.zip](https://github.com/usgs/groundmotion-processing/files/7637360/20000925155013.zip)

**Comment by emthompson-usgs** [comment]
This is the intended behavior. See: 
https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/core/stationstream.py#L257
We generally don't want to use single components of streams.
