### ISSUE TITLE
handling colocated instruments heicherarchy

### ISSUE THREAD

**Issue by hadigh** [usgs/groundmotion-processing#804]
**Is your feature request related to a problem? Please describe.**

In case of colocated sensors, can the program automatically move on to the next instrument in the hierarchy order if the prioritize (hence selected) instrumet fail for example due to SNR issues.
I have attached one example to this message. Here the HH? Channels are of acceptable quality but are expectedly rejected as they are colocated with HN? Ones; but at the same time HN? Ones are rejected due to SNR issues.  

**Describe the solution you'd like**
In the above example, i would expect the program to process HH? and compute gm metrics given that HN? channells are expectadly rejected due to low SNR.

[20120323092519.zip](https://github.com/usgs/groundmotion-processing/files/7658087/20120323092519.zip)

**Comment by emthompson-usgs** [comment]
Yes, this is a good idea. I think it will require a non-trivial change to the code, though, so it will take a while for me to find time to do this. The difficulty is that at the point in the code where the duplicate check is done, the QA checks have not yet been performed, so I'll need to reorganize the code.

**Comment by emthompson-usgs** [comment]
Actually, this looks easier than I realized. I should have this done shortly.
