### ISSUE TITLE
export metric tables when all the records for an event fail!

### ISSUE THREAD

**Issue by hadigh** [usgs/groundmotion-processing#816]
**Is your feature request related to a problem? Please describe.**
if all of the waveforms within an event fail (for example due to SNR issue), running export_metric_tables (after running "wm", and "sm") generates an error, stopping the code to move to the next event! 

**Describe the solution you'd like**
In such cases, I would suggest adding an "exception" to simply ignore such events and move to the next available event.

**Comment by emthompson-usgs** [comment]
Thanks for pointing this out. I thought we had already fixed this but it must have been a variation on this issue.

**Comment by emthompson-usgs** [comment]
Please re-open if this doesn't solve the problem.
