### ISSUE TITLE
Name of class for working with our flavor of ASDF?

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#86]
Effectively, we are putting in some addition expected structure within the ASDF standard. We will be essentially using ASDF to hold our StreamCollection data. What should we call this? We were thinking of something like StreamWorkspace. @baagaard-usgs let us know what you think please.

**Comment by baagaard-usgs** [comment]
StreamWorkspace or simply Workspace seem reasonable to me.

**Comment by emthompson-usgs** [comment]
Ok. One concern is that it may get confusing with the `groundmotion-workspace` repository, but I think we can worry about where the code lives and whether or not it should be split up into that workspace at a later time when things have matured a bit.

**Comment by mhearne-usgs** [comment]
See attached text file (rename to .py to see syntax highlighting) with strawman class definition for StreamWorkspace() class.
[stream_workspace.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5617f9c98fe1a91300dc7968/125516c66e82c728ace21e0d46fb808826838e9698e6ad48b74df1972c046b313916ac217586f76ae5002e025a5b1fa9495f0d41aafbdc23a6b23c24dc5d03eed43c4d68d47f40f2ecdd42e64bef62994597b7b4804dc5ed3c22e58b8f48381b021b9bb2.txt)

**Comment by baagaard-usgs** [comment]
What is the functionality of the workspace? Is it intended to manage workspace objects (event, streams, etc) in memory or is it a high-level interface for reading/writing parts of the ASDF file?

The constructor seems to really be a save() method as it looks like it is intended to create an ASDF file.

**Comment by mhearne-usgs** [comment]
Closed with PR #118
