### ISSUE TITLE
Module Not Being Found

### ISSUE THREAD

**Issue by dchurchwell-usgs** [usgs/groundmotion-processing#873]
When processing data, gmprocess is trying to import ``auto_fchp``, but the module is not being found.

Run,
``gmrecords download -e *insert event* ``
``gmrecords assemble ``
``gmrecords process ``

And you'll get: ``ModuleNotFoundError: No module named 'gmprocess.waveform_processing.auto_fchp'
``

There seem to be files [here](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/waveform_processing/auto_fchp.c) and [here](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/waveform_processing/auto_fchp.pyx), but I am not sure which one the code is trying to import. The error is occurring at [this](https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/waveform_processing/adjust_highpass_ridder.py#L5) location in the code.

**Comment by emthompson-usgs** [comment]
Okay, I think I realized what the issue is. Please ignore my previous comment. There's a new cython module that that package uses and so if you are using a previously built virtual environment then you have to re-rn `pip install -e .` to force it to re-compile and install the new cython code.
