### ISSUE TITLE
Very small and unusual PGA values for some ground motions 

### ISSUE THREAD

**Issue by jcy-go** [usgs/groundmotion-processing#876]
Extremely small PGA values observed for some records. For example, the PGA for NS component is 3.67e-5g, but the value for EW component is 5.07e-14g. The record was observed at station AZ.YAQ for earthquake with id of ci9805021. The unprocessed and processed time series for this example are belo.

<img width="754" alt="Screen Shot 2022-02-04 at 3 51 23 PM" src="https://user-images.githubusercontent.com/32785330/152601519-da2d94de-1d35-4d37-bdf3-f1b094924d11.png">

<img width="672" alt="image" src="https://user-images.githubusercontent.com/32785330/152600630-08054de2-4e28-4ed3-9ed4-a8adb3e0da4b.png">

More similar processed records were observed from our dataset as shown [here](https://user-images.githubusercontent.com/32785330/152602165-c3b09a1d-aea6-4c55-8e9d-c0a0e4e76fa6.jpeg).

Environment:
OS: macOS Monterey v12.1
Python Version 3.8
Numpy Version 1.21.5

**Comment by emthompson-usgs** [comment]
I cannot reproduce this with the current version of the code. Can you update and see if that resolves this? 
<img width="827" alt="Screen Shot 2022-02-04 at 2 24 43 PM" src="https://user-images.githubusercontent.com/15928870/152605303-5b65f965-7fb2-49a7-a72f-b0b08be8287f.png">

**Comment by jcy-go** [comment]
I am sorry for the late reply. I have reprocessed this event with the latest gmprocess, and I did not get the weird PGA values again.
