### ISSUE TITLE
Reprocessing human-reviewed h5 file

### ISSUE THREAD

**Issue by meramossepu** [usgs/groundmotion-processing#896]
**Is your feature request related to a problem? Please describe.**

We have created a GUI in Jupyter notebooks that allows us to make a human revision of the processed records. This is to avoid the acceptance of noisy records that passed the failing criteria or improve the selection of high-pass corner frequencies. The GUI adds an entry in the "dataset.auxiliary_data.review" group that informs the user if the record was accepted, rejected and if the high-pass corner frequency was modified. The current gmprocess does not read this entry and it does not reprocess the record.

**Describe the solution you'd like**

An extra step is needed so gmprocess could read the modified h5 file and reprocess the records that have modified corner frequencies

**Describe alternatives you've considered**

N/A

**Additional context**

The modifications to the h5 file are depicted in the following manner:
review:
![image (1)](https://user-images.githubusercontent.com/96747098/158702477-fd495683-c0ff-4347-93cd-a717da6359fe.png)

corner_frequency.highpass:
![image (2)](https://user-images.githubusercontent.com/96747098/158702527-bbedf08c-ec57-43a5-a552-4ebe41172118.png)

accepted:
![image (3)](https://user-images.githubusercontent.com/96747098/158702542-8537fa63-55db-43ac-8dc2-2333dfc3c2fa.png)

**Comment by emthompson-usgs** [comment]
Please add the notebook to the repository so that I can run it. If I can do that and get an example ASDF file then I can add the functionality to gmprocess to make use of the review data.

**Comment by meramossepu** [comment]
[ProcessorGUI.zip](https://github.com/usgs/groundmotion-processing/files/8289279/ProcessorGUI.zip)

Let me know if you are able to open it and run it.
