### ISSUE TITLE
 'assemble' fails when encountering .DS_Store files during shutil tmp directory creation and deletion 

### ISSUE THREAD

**Issue by gferragu** [usgs/groundmotion-processing#899]
**Describe the bug**
When the auto-generated `.DS_Store` files are created by Mac's Finder in a gmprocess project's subdirectories (data/raw/ for example), subcommand `assemble` may fail due to an error encountered in `read_directory.py` This is likely due to `.DS_Store` file permissions, which results in a non-empty directory during the call to `shutil.rmtree()` [here](https://github.com/usgs/groundmotion-processing/blob/28c586fd4aa3f013b6b6fe5965f3dfe354cb5b0a/gmprocess/io/read_directory.py#L71)

Adding `.DS_Store` to the EXT_IGNORE list does not fix the issue to the how ignored files are checked [here](https://github.com/usgs/groundmotion-processing/blob/28c586fd4aa3f013b6b6fe5965f3dfe354cb5b0a/gmprocess/io/read_directory.py#L58).

A fix and possible improvement to the existing method of looping over files and checking their extensions could be to use the built-in `shutil.ignore_patterns()` function, which can be passed as a parameter to the initial call of `shutil.copytree()` [here](https://github.com/usgs/groundmotion-processing/blob/28c586fd4aa3f013b6b6fe5965f3dfe354cb5b0a/gmprocess/io/read_directory.py#L48) so that unwanted files (both `.DS_Store` and those with extensions listed in `EXT_IGNORE`) are never copied in the first place.

**Comment by emthompson-usgs** [comment]
I don't really follow what is happening. I don't think that it should matter if .DS_Store is empty since shutil.rmtree removes a directory tree, and there are already many non empty directories in the path handed to it. If it is a permissions issue in that your user cannot delete the directory, that doesn't seem like a gmprocess issue.

**Comment by emthompson-usgs** [comment]
Closd by #901.
