### ISSUE TITLE
KeyError when I run gmrecords init and gmrecords projects -c

### ISSUE THREAD

**Issue by jkim1208** [usgs/groundmotion-processing#902]
**Describe the bug**
When I run gmrecords init and gmrecords projects -c, KeyError comes out.

**To Reproduce**
Traceback (most recent call last):
  File "/home/jkim/anaconda3/envs/gmprocess/bin/gmrecords", line 33, in <module>
    sys.exit(load_entry_point('gmprocess', 'console_scripts', 'gmrecords')())
  File "/home/jkim/Downloads/groundmotion-processing/gmprocess/bin/gmrecords.py", line 6, in main
    GMrecordsApp().main()
  File "/home/jkim/Downloads/groundmotion-processing/gmprocess/apps/gmrecords.py", line 72, in __init__
    self._load_config()
  File "/home/jkim/Downloads/groundmotion-processing/gmprocess/apps/gmrecords.py", line 132, in _load_config
    self.current_project = self.projects_conf["projects"][self.project]
  File "/home/jkim/anaconda3/envs/gmprocess/lib/python3.9/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'None'

**Environmnet (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Python Version [3.8]

**Comment by emthompson-usgs** [comment]
Thanks for the report. Can you include the terminal log that you see after running `gmrecords proj -c`? It should either prompt you for responses or print a message. For example, here's what I get if I run thee command and then give an empty response to the prompt that asks for a project title:
```
$ gmrecords proj -c
INFO 2022-03-30 09:25:09 | gmrecords._initialize: Logging level includes INFO.
INFO 2022-03-30 09:25:09 | gmrecords._initialize: PROJECTS_PATH: /Users/emthompson/.gmprocess
INFO 2022-03-30 09:25:09 | projects.main: Running subcommand 'projects'
Please enter a project title: [default]
Project 'default' already exists.  Run 'gmrecords projects -l' to see existing projects.
```

**Comment by emthompson-usgs** [comment]
You can ignore my request. I think I figured out how this can happen and I should have a fix shortly.

**Comment by emthompson-usgs** [comment]
Please update to the latest version of the code and let us know if the problem is resolved. If it is not, reopen the issue.
