### ISSUE TITLE
Replace os.path with the Pathlib library

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#926]
Apparently Pathlib is the new hotness and I've been a neophobe by avoiding it:
https://towardsdatascience.com/why-you-should-start-using-pathlib-as-an-alternative-to-the-os-module-d9eccd994745

**Comment by arkottke** [comment]
It has been hot for years now!

**Comment by emthompson-usgs** [comment]
"New" is a relative term...

**Comment by emthompson-usgs** [comment]
Lots of the code is now using pathlib. Closing this issue.
