### ISSUE TITLE
Multiple Events using Circular Domain Fails for FDSN

### ISSUE THREAD

**Issue by smithj382** [usgs/groundmotion-processing#944]
If I run the downloader configured for FDSN for multiple events (using the -t flag), the second event fails with the message:

```
    if dconf["use_epicenter"]:
  File "/Users/jamesasmith/miniconda/envs/gmprocess/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'use_epicenter'
```

**To Reproduce**
Run ```gmprocess download -t eventids.txt``` with more than one eventid in the text file eventids.txt. 
Here are the two comcat ids I used:
uu60041537
uu60363667

The bug is a result of popping values (ie: ```dconf.pop("use_epicenter")) in the fdsn_fetcher.py file.

Since the config file is setup to be only read once, this line pops (removes) this variable and it is transient so that the second event won't have access to it. I suggest removing all .pop statements and not using the ** shortcut (ie explicitly give the parameters):

   ```domain = CircularDomain(dconf["latitude"], dconf["longitude"], dconf["minradius"], dconf["maxradius"])```

One could also read the config file anew for each event, but that seems like a really bad idea. Ideally, this bug have been caught by the tests. I do not see a FDSN fetcher test for more than one event in the current code. So it might be worth adding a test for more than one event for FDSN fetcher. If you are okay with my fix (ie removing pop statements and giving parameters explicitly), I can make a pull request today, but we should discuss adding more tests for this sort of bug. If you have a better solution, let me know. Thanks!

**Comment by emthompson-usgs** [comment]
I'll deal with this, but the reason there's no unit test for this is because unit tests have to be able to work offline. So the unit tests would need some kind of mocked up connection, probably using the vcrpy package and I haven't learned how to use it yet. 

Also, a large reason for the refactor was to avoid hard coding the arguments so I'm not going to do that.
