### ISSUE TITLE
Support for multiple config files

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#99]
Allow for a default config and then let it get overwritten by incomplete configs.

**Comment by baagaard-usgs** [comment]
I have code and a test for merging dictionaries. Where should they go?

**Comment by emthompson-usgs** [comment]
I think probably here: 
https://github.com/usgs/groundmotion-processing/blob/master/gmprocess/config.py
I guess there's still an open question of how multiple configs will be specified/discovered. I'm open to ideas for how this should be done. My initial thought is that we could modify `get_config` so that it combines all configs discovered in `.gmprocess` thereby getting rid of the need for the `picker` argument (and the thing that `get_config` returns would always be a comprehensive config regardless of how it is getting called). Then we could add an optional argument with a path to another config that would get merged (and take precedence) over the default confs that were found in `.gmprocess`. If we did this, we might want to add a top level key to `picker.yml` so that it's contents remain distinct once merged with `config.yml`.

**Comment by baagaard-usgs** [comment]
Merging config dictionaries implemented in PR https://github.com/usgs/groundmotion-processing/pull/114.

Still need to modify `get_config` to deal with multiple config files.
